### ISSUE TITLE
Runtime error: slice bounds out of range [:9] with capacity 0

### ISSUE THREAD

**Issue by magicaltoast** [JustTalDevelops/go-hcaptcha#13]
While trying to use an example code, go panics with error shown below
```
panic: runtime error: slice bounds out of range [:9] with capacity 0

goroutine 75 [running]:
github.com/justtaldevelops/go-hcaptcha.(*Challenge).simulateMouseMovements(0xc000314000, {0x19ade40, 0x0, 0x0})
        /home/idk/golang_onnx/go-hcaptcha/challenge.go:236 +0xa85
github.com/justtaldevelops/go-hcaptcha.(*Challenge).Solve(0xc000314000, {0x1214e80, 0xc0004d2000})
        /home/idk/golang_onnx/go-hcaptcha/challenge.go:114 +0x3fa
main.iterSolve(0xc0003ad0a0, 0xc000065f90)
```

**Comment by magicaltoast** [comment]
I found out it is caused when hcaptcha response is sth like that.

So you can clearly see by reading char by char it's caused by ``Over rate limit``
```js
{
   "0":"O",
   "1":"v",
   "2":"e",
   "3":"r",
   "4":" ",
   "5":"r",
   "6":"a",
   "7":"t",
   "8":"e",
   "9":" ",
   "10":"l",
   "11":"i",
   "12":"m",
   "13":"i",
   "14":"t",
   "c":{
      "type":"hsw",
      "req":"...Some random letter"
   }
}
```

**Comment by JustTalDevelops** [comment]
Oh, I appreciate the help! Any chance you know where exactly this rate limit is usually sent, like on the initial captcha request phase, submitting, etc?

**Comment by magicaltoast** [comment]
@JustTalDevelops I believe that in the initial captcha request, I solved it quickly by checking the length of tasks is greater than zero

**Comment by JustTalDevelops** [comment]
Ah, that makes sense. I'll make a patch sometime today and update this issue then.

**Comment by JustTalDevelops** [comment]
Resolved by the latest commit.
