### ISSUE TITLE
Native HSL solving

### ISSUE THREAD

**Issue by post04** [JustTalDevelops/go-hcaptcha#15]
Hey, I saw how you were solving HSL right now. It can be done natively with golang pretty easily. Here's my rewrite to HSL to golang you can use if you'd like, though I'd suggest cleaning it up lol.

https://gist.github.com/post04/4e8f60c94661979bcbef1ab60232891e

**Comment by JustTalDevelops** [comment]
Heya! I'll definitely look into revising that code to work with go-hcaptcha, and I'll keep this open until then. Appreciate the help!

**Comment by JustTalDevelops** [comment]
Quick question - is there a reason why n (the function) is not being used?

**Comment by JustTalDevelops** [comment]
I'm just confused because e isn't using n at all, leaving a bunch of extra, useless code. Is this correct?

**Comment by JustTalDevelops** [comment]
If so, I'd assume you could just shorten it all down to this:
![image](https://user-images.githubusercontent.com/39247615/142741493-fbc8e5c8-eed3-4c82-aaab-36300faa9483.png)

**Comment by post04** [comment]
> I'm just confused because e isn't using n at all, leaving a bunch of extra, useless code. Is this correct?

It probably is, I removed some useless function uses but never really cleaned the code up. The code is well over 4 months old at this point.

**Comment by JustTalDevelops** [comment]
Ah okay. Needless to say, appreciate the contribution!

**Comment by post04** [comment]
> Ah okay. Needless to say, appreciate the contribution!

For sure man! If I ever find a way to get past HSW I've gotcha on that. Though I will say if you submit an HSL token for HSW it will just serve you a captcha of which I think HSL would be valid on. I'm not 100% sure about that so you'd have to test around with it.

**Comment by ghost** [comment]
Sorry for re-opening this, 
First, I would like to thank you post for the code you provided, was really helpful, however, the latest argument in the HSL hash can't be "1" every time.
So I completed the code "missing", and now it's working flawlessly, see test file: https://github.com/bytixo/hsl-go

**Comment by post04** [comment]
> Sorry for re-opening this, 
> 
> First, I would like to thank you post for the code you provided, was really helpful, however, the latest argument in the HSL hash can't be "1" every time.
> 
> So I completed the code "missing", and now it's working flawlessly, see test file: https://github.com/bytixo/hsl-go

I appreciate the information, when I was first making this I did it in a solid 8 hour code session so it was definitely scuffed 😅. Also you can actually fully pass captchas with HSL with no images by using the cookie "hc_accessability" (may have spelled it wrong), I can give you a code example if you're interested in that!

Hope you had a great Christmas if you celebrate!

**Comment by ghost** [comment]
> > Sorry for re-opening this,
> > First, I would like to thank you post for the code you provided, was really helpful, however, the latest argument in the HSL hash can't be "1" every time.
> > So I completed the code "missing", and now it's working flawlessly, see test file: https://github.com/bytixo/hsl-go
> 
> I appreciate the information, when I was first making this I did it in a solid 8 hour code session so it was definitely scuffed 😅. Also you can actually fully pass captchas with HSL with no images by using the cookie "hc_accessability" (may have spelled it wrong), I can give you a code example if you're interested in that!
> 
> Hope you had a great Christmas if you celebrate!

Hello hope you add a great Christmas too!
This is exactly what I'm trying to do and I was struggling with HSL solving until i found this issue, so now I'll try to send the final request correctly.
But rn I'm getting a wrong response (they send a new challenge) and I don't really know where I'm wrong, so yeah a code example would appreciated
Have a great day/night.
