### ISSUE TITLE
YOLOv3 solver not working properly

### ISSUE THREAD

**Issue by BitSleek** [JustTalDevelops/go-hcaptcha#16]
Hi @JustTalDevelops,

I just setup everything to run this package. When I start to solve a captcha (just tried using the example) it starts normally but it doesn't detect anything in any image so it just keep looping sending the captcha with 0/9 tasks given.
I tried to use YoloV3 separately and it worked without any problem, so I think it's not a configuration problem (I don't even get errors executing the example with this package).

How can I solve this problem?

I'm also leaving the console output here:
```
2021/11/20 20:24:58 Downloading browsers...
2021/11/20 20:25:01 Downloaded browsers successfully
DEBU[0000] Verifying site configuration...
INFO[0001] Requesting captcha...
DEBU[0002] Solving challenge with *hcaptcha.YOLOSolver... 
DEBU[0002] The type of challenge is "image_label_binary" 
DEBU[0002] The target object is "bicycle"
DEBU[0044] Decided on 0/9 of the tasks given!
DEBU[0044] Simulating mouse movements on tiles...       
DEBU[0045] submit request was rejected
DEBU[0045] Verifying site configuration...
INFO[0046] Requesting captcha...
DEBU[0047] Solving challenge with *hcaptcha.YOLOSolver... 
DEBU[0047] The type of challenge is "image_label_binary" 
DEBU[0047] The target object is "truck"
DEBU[0093] Decided on 0/9 of the tasks given!
DEBU[0093] Simulating mouse movements on tiles...       
DEBU[0094] submit request was rejected
etc...
```

Just to make sure I added my code (PS. This is literally my first code in GOLang and I'm not interested in studying it, I just need to solve captchas xD, I hope I didn't make any error):
```golang
package main

import (
    gohcaptcha "github.com/justtaldevelops/go-hcaptcha"
)

func main() {
    for {
	    c, err := gohcaptcha.NewChallenge("http://democaptcha.com/demo-form-eng/hcaptcha.html", "51829642-2cda-4b09-896c-594f89d700cc")
	    if err != nil {
		    panic(err)
	    }
	    err = c.Solve(&gohcaptcha.YOLOSolver{Log: c.Logger()})
	    if err != nil {
		    c.Logger().Debug(err)
		    continue
	    }
	    c.Logger().Info(c.Token())
	    break
    }
}
```

**Comment by JustTalDevelops** [comment]
Hey!

Please make sure you download the `yolov3.weights`, `yolov3.cfg`, and `coco.names` files and move them to a new folder in your working directory under the name `yolo`. You can a link to the downloads for all three on the README, under the Installation section.

Without these files, the YOLOSolver will fail to function normally, and won't error as I (for some reason, this should be changed honestly) ignored the error from the YOLO network creation.

Please let me know if that fixes your issues.

**Comment by BitSleek** [comment]
@JustTalDevelops, I already did that, that's my directory tree:
```
GOLang
  | - yolo
    | - coco.names
    | - yolov3.cfg
    | - yolov3.weights
  | - go.mod
  | - go.sum
  | - main.go (Where I wrote the code)
```

**Comment by JustTalDevelops** [comment]
This seems to be more of an issue with gocv or the Go YOLOv3 implementation then, as all go-hcaptcha does is access them.

**Comment by JustTalDevelops** [comment]
Have you tried using gocv or Go YOLOv3 by itself?

**Comment by BitSleek** [comment]
I only tried to use YOLOv3 by themselves, what should I do for gocv?

**Comment by JustTalDevelops** [comment]
I'm not sure, but I just tried the example YOLOv3 solver in captcha_test.go and it worked just fine for me. I'm assuming you set up gocv or Go YOLOv3 incorrectly.
![image](https://user-images.githubusercontent.com/39247615/142740932-d2b48cfe-8af6-4399-a411-a211131c80cc.png)

**Comment by JustTalDevelops** [comment]
> I only tried to use YOLOv3 by themselves, what should I do for gocv?

There are specific prerequisites for gocv, as mentioned on the README. You need to set them up in order to properly use the YOLO solver, as Go YOLOv3 requires it.

**Comment by BitSleek** [comment]
I followed the official guide for gocv: https://gocv.io/getting-started/windows/
I only noticed that your package installs an older version of gocv and the same thing for OpenCV, is that a problem?

**Comment by JustTalDevelops** [comment]
Have you tried running the gocv example, to make sure you set it up correctly? And I don't think it should cause issues, but you can try updating it yourself and seeing if it helps.

**Comment by BitSleek** [comment]
If you mean the version example, I already tried it and it outputs this as normal:
```
gocv version: 0.28.0
opencv lib version: 4.5.3
```

**Comment by JustTalDevelops** [comment]
Oh no, I meant an actual example, say face detect.

**Comment by JustTalDevelops** [comment]
I'm not sure what exactly could cause issues here on my end though, as all I've really done is accessed the gocv & go-yolov3 APIs.

**Comment by BitSleek** [comment]
I just tried the face detect example and works perfectly.

**Comment by BitSleek** [comment]
Some time ago I tried to scrape manually a HCaptcha: I waited for the image element and then I took it, but sometimes that element appears when still loading so it takes a blank photo. Is this an actual problem?

**Comment by JustTalDevelops** [comment]
I don't know. Another possibility is that your IP is banned from getting images from the hCaptcha API. I'm not sure. All I know is that it's somehow working on my end and not yours.

**Comment by JustTalDevelops** [comment]
Perhaps try it with a residential VPN?

**Comment by BitSleek** [comment]
Sadly still not working, my IP is not blacklisted.
Can I do something to see if there is any error?

Can you also check what's yours gocv and OpenCV version?

**Comment by JustTalDevelops** [comment]
My version is the same as yours it seems. I don't know what the issue is, but whatever it is, I'm pretty positive that it's not an issue with this library. If you'd like, you can try to fork this repository and try to debug parts to see if you can narrow it down, but I've had many people use the library and none of them have had any issues with it. I'm going to close this for now, but if you get any further in tracking down where this bug originates, please let me know and make a new issue.

**Comment by BitSleek** [comment]
I finally found out what the problem is, after hours of debugging a language that I don't know...
It's a problem caused by YOLOv3, probably a newer version of it. I'm gonna send a pull request.

**Comment by chris-aeviator** [comment]
can confirm it works on a fresh install from this repo

**Comment by V4NSH4J** [comment]
> I finally found out what the problem is, after hours of debugging a language that I don't know... It's a problem caused by YOLOv3, probably a newer version of it. I'm gonna send a pull request.

Hey, could you elaborate on fixing this issue? I'm facing the exact same thing.
