### ISSUE TITLE
About building

### ISSUE THREAD

**Issue by klotein** [JustTalDevelops/go-hcaptcha#2]
Hi, i am trying to use this module.

these my codes ,can you check did i do any correct?

`
import (
"github.com/justtaldevelops/hcaptcha-solver-go"
)
err := os.Setenv("GOOGLE_APPLICATION_CREDENTIALS", "/home/pcuser/testg/test.json")
if err != nil {
    panic(err)
}

// Create the solver with the default options.
s, err := hcaptcha.NewSolver("https://testsite.com")
if err != nil {
    panic(err)
}
defer s.Close()

// We provide a deadline that the solver must have the solution done by.
// If the deadline is not reached, an error is sent instead of the solution.
solution, err := s.Solve(time.Now().Add(3 * time.Minute))
if err != nil {
    panic(err)
}
// P0_eyJ0eXAiOiJKV1Q...
fmt.Println(solution)`

and im trying `go build` but i got `go: go.mod file not found in current directory or any parent directory; see 'go help modules'

help pls.
`

**Comment by JustTalDevelops** [comment]
Did you even read the error?

**Comment by klotein** [comment]
> Did you even read the error?

I did but i don't have any experience about golang.

**Comment by JustTalDevelops** [comment]
Also that code is very wrong, refer to the example. If you don't have experience with GoLang, use the API instead.

**Comment by JustTalDevelops** [comment]
Use the API, it's on my GitHub profile.

**Comment by klotein** [comment]
> Use the API, it's on my GitHub profile.

Its look hard than this. im using on debain. 
err := os.Setenv("GOOGLE_APPLICATION_CREDENTIALS", "C:\\Users\\JustTal\\VisionAPI\\Project.json")
if err != nil {
    panic(err)
}
can you show this edit for me on debain? need a api key?

**Comment by JustTalDevelops** [comment]
> > Use the API, it's on my GitHub profile.
> 
> Its look hard than this. im using on debain.
> err := os.Setenv("GOOGLE_APPLICATION_CREDENTIALS", "C:\Users\JustTal\VisionAPI\Project.json")
> if err != nil {
> panic(err)
> }
> can you show this edit for me on debain? need a api key?

No, it isn't. All you need to do is `go install github.com/justtaldevelops/hcaptcha-solver-api`, then `export GOOGLE_APPLICATION_CREDENTIALS="/home/pcuser/testg/test.json"` and then `hcaptcha-solver-api`

**Comment by klotein** [comment]
i can't use your api for my project.

i looked your example code and i got true codes.

but im getting new error when i try "go build"

package github.com/justtaldevelops/hcaptcha-solver-go
        imports github.com/justtaldevelops/hcaptcha-solver-go: import cycle not allowed
