### ISSUE TITLE
Update readme with steps describing howto obtain  Yolov3 weights, config, names

### ISSUE THREAD

**Issue by chris-aeviator** [JustTalDevelops/go-hcaptcha#21]
The provided repository does not provide the files suggested in #16 . Where can I find the model weights, config, names?

![grafik](https://user-images.githubusercontent.com/11522213/144220509-ad1b19cc-0632-43b0-a5fc-bb321c8c5468.png)

EDIT:

the Yolov3 readme suggests running `make models`, it is unclear if this is the step neccessary since go-hcaptcha readme mentions **downloading** them.

UPDATE:

since neither Yolov3 repository nor go-hcaptcha mention how to obtain the desired files it would be benefitial to new users if a section

> # Howto obtain Weights, Names & config from Yolov3
> 1) git clone https://github.com/wimspaargaren/yolov3
> 2) make models
> 3) cp -r [yolov3path]/data/yolov3 [go-hcaptcha-project-path]/

would be added to the readme

**Comment by BitSleek** [comment]
Actually there is an easier way. You can get the links from the getModels.sh file (https://github.com/wimspaargaren/yolov3/blob/master/getModels.sh), just run the commands and if you want change the "mkdir" to another directory.
