### ISSUE TITLE
[question] I am not able to run it

### ISSUE THREAD

**Issue by Ryxwaer** [JustTalDevelops/go-hcaptcha#28]
Hello,
I have some problems runng this project. This is the first time I see go lang so the problem is probably on my side. when I clon this repository and build everything in it by `go build` it won't generate any runnable file. As I tought it should. 
So pardon me for stupid question but how am I supposed to run this? I am desperate for help. If you can point me to the right direction I would be glad.
Thanks.

**Comment by JustTalDevelops** [comment]
This is a library, not a program.
