### ISSUE TITLE
Any similar library for reCAPTCHA

### ISSUE THREAD

**Issue by ghost** [JustTalDevelops/go-hcaptcha#29]
Is there any similar library that solves reCAPTCHA v2 with tiled images?

I tried to solve a reCAPTCHA using this, but I'm getting this error : 
```
panic: site key is invalid
```
I assume this is because of the challenge being reCAPTCHA and not a hCAPTCHA. 

Thanks

**Comment by JustTalDevelops** [comment]
Yes, as the name suggests, this is hCaptcha only.
