### ISSUE TITLE
Invalid-data issue

### ISSUE THREAD

**Issue by RichDavis1** [JustTalDevelops/go-hcaptcha#6]
Hey there, cool lib. I know this isn't meant for production or anything but I wanted to see if you were able to get past the ```{"success":false,"error-codes":["invalid-data"]}``` issue?

I saw your response on gitmemory and am curious to see if you found a solution?

**Comment by JustTalDevelops** [comment]
Oh hey, thanks for checking it out! Unfortunately I haven't touched this in a few months and I've forgotten a lot about the issues I had prior to it working, so I'm not exactly sure what I did to fix it for me. Feel free to look through my code though and make assumptions yourself.
