### ISSUE TITLE
contact info

### ISSUE THREAD

**Issue by andress134** [JustTalDevelops/go-hcaptcha#7]
Hello sir, where i can contact you? i have sent you an email to justtal@protonmail.com

**Comment by JustTalDevelops** [comment]
Hi there!

If the comment is related to hcaptcha-solver-go, I'm currently not too active on this project anymore but I'm planning on returning to it soon and updating it to their new API.

Feel free to leave an issue about any issues you have with the project and I'd be happy to help, in any way I can.

If it's unrelated to this project, send me an email at justtal@protonmail.com and I'll probably respond to you. I have a load of emails, so if I don't get back to you immediately, feel free to send another.
