### ISSUE TITLE
Update the solver to the latest hCaptcha API

### ISSUE THREAD

**Issue by JustTalDevelops** [JustTalDevelops/go-hcaptcha#8]
Haven't been too active here but I am planning on soon. I'm not sure on what more measures have been implemented to prevent bots, so help from others will be appreciated.

**Comment by DortDev** [comment]
https://github.com/h0nde/py-hcaptcha
I'm not sure if the owner would allow you to use any code from here, but this may be of big help

https://github.com/hitthemoney/hcaptcha-solver this one also works too.

**Comment by JustTalDevelops** [comment]
This is currently being worked on in `feature/v2`, heavily based off of h0nde's implementation right now. Plan to be using YOLOv3 for Go as the main solver, so Google Vision won't be a requirement, but I do want to abstract the API enough to the point where you can embed custom solvers.
